// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/file/uploadFile": {
            "post": {
                "description": "upload file.",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "file"
                ],
                "summary": "upload file.",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FileItem"
                        }
                    }
                }
            }
        },
        "/teamview/getRoomList": {
            "post": {
                "description": "获取房间列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "获取房间列表",
                "parameters": [
                    {
                        "description": "获取房间列表参数",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqGetRoomList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "进行中房间列表",
                        "schema": {
                            "$ref": "#/definitions/models.RespOngoingRoomList"
                        }
                    },
                    "2002": {
                        "description": "结束房间列表(为了区分文档，code使用2002)",
                        "schema": {
                            "$ref": "#/definitions/models.RespFinishedRoomList"
                        }
                    }
                }
            }
        },
        "/teamview/getRtcToken": {
            "post": {
                "description": "生成rtcToken",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "vod"
                ],
                "summary": "生成rtcToken",
                "parameters": [
                    {
                        "description": "录像频道id和uid参数",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ParamsTestVod"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiJson"
                        }
                    }
                }
            }
        },
        "/teamview/getSpecialist": {
            "post": {
                "description": "获取专家列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "获取专家列表",
                "parameters": [
                    {
                        "description": "获取专家列表参数",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ParamPageList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RespGetSpecialist"
                        }
                    }
                }
            }
        },
        "/teamview/getUserInfo": {
            "post": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "description": "获取用户信息",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqUId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserInfo"
                        }
                    }
                }
            }
        },
        "/teamview/insertRoom": {
            "post": {
                "description": "创建房间",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "创建房间",
                "parameters": [
                    {
                        "description": "创建房间",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqInsertRoom"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RespInsertRoom"
                        }
                    }
                }
            }
        },
        "/teamview/insertUserOnlineInfo": {
            "post": {
                "description": "记录用户在线心跳包信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "记录用户在线心跳包信息",
                "parameters": [
                    {
                        "description": "记录用户在线心跳包信息参数",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqInsertUserOnlineInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiJson"
                        }
                    }
                }
            }
        },
        "/teamview/joinRoom": {
            "post": {
                "description": "加入房间",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "加入房间",
                "parameters": [
                    {
                        "description": "加入房间参数",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqJoinRoom"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RespJoinRoom"
                        }
                    }
                }
            }
        },
        "/teamview/leaveRoom": {
            "post": {
                "description": "用户离开房间",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "用户离开房间",
                "parameters": [
                    {
                        "description": "用户离开房间",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqLeaveRoom"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiJson"
                        }
                    }
                }
            }
        },
        "/teamview/signIn": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录参数",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqSignIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RespSignIn"
                        }
                    }
                }
            }
        },
        "/teamview/startVod": {
            "post": {
                "description": "录制",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "vod"
                ],
                "summary": "录制",
                "parameters": [
                    {
                        "description": "录像频道id和uid参数",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ParamsTestVod"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RespStartVodRecording"
                        }
                    }
                }
            }
        },
        "/teamview/teamViewRtcNotify": {
            "post": {
                "description": "消息回调",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "消息回调",
                "parameters": [
                    {
                        "description": "消息回调",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqTeamViewRtcNotify"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiJson"
                        }
                    }
                }
            }
        },
        "/teamview/teamViewVodNotify": {
            "post": {
                "description": "录像回调",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "teamview"
                ],
                "summary": "录像回调",
                "parameters": [
                    {
                        "description": "录像回调",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReqTeamViewVodNotify"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ApiJson"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ApiJson": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据",
                    "type": "object"
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "models.FileItem": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "文件名字",
                    "type": "string"
                },
                "url": {
                    "description": "文件url",
                    "type": "string"
                }
            }
        },
        "models.FinishedRoomInfo": {
            "type": "object",
            "properties": {
                "roomFileUrl": {
                    "description": "房间录像文件url",
                    "type": "string"
                },
                "roomHostId": {
                    "description": "房主uid",
                    "type": "string"
                },
                "roomId": {
                    "description": "房间id",
                    "type": "string"
                },
                "roomName": {
                    "description": "房间名称",
                    "type": "string"
                },
                "roomStartTs": {
                    "description": "房间录制开始时间(单位:毫秒)",
                    "type": "integer"
                },
                "roomState": {
                    "description": "房间状态(1:结束,2:进行中,3:转码中)",
                    "type": "integer"
                },
                "roomStopTs": {
                    "description": "房间录制结束时间(单位:毫秒)",
                    "type": "integer"
                },
                "roomTs": {
                    "description": "房间创建时间戳(单位:秒)",
                    "type": "integer"
                },
                "userName": {
                    "description": "房主名",
                    "type": "string"
                }
            }
        },
        "models.OnGoingRoomInfo": {
            "type": "object",
            "properties": {
                "roomHostId": {
                    "description": "房主uid",
                    "type": "string"
                },
                "roomId": {
                    "description": "房间id",
                    "type": "string"
                },
                "roomName": {
                    "description": "房间名称",
                    "type": "string"
                },
                "roomState": {
                    "description": "房间状态(1:结束,2:进行中,3:转码中)",
                    "type": "integer"
                },
                "roomTs": {
                    "description": "房间创建时间戳(单位:秒)",
                    "type": "integer"
                },
                "userName": {
                    "description": "房主名",
                    "type": "string"
                }
            }
        },
        "models.ParamPageList": {
            "type": "object",
            "properties": {
                "pageNum": {
                    "description": "页码（从1开始）",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "单页显示条数",
                    "type": "integer"
                }
            }
        },
        "models.ParamsTestVod": {
            "type": "object",
            "properties": {
                "cname": {
                    "description": "频道id",
                    "type": "string"
                },
                "uid": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "models.Payload": {
            "type": "object",
            "properties": {
                "Ts": {
                    "description": "事件发生的时间戳（单位：毫秒）",
                    "type": "integer"
                },
                "appId": {
                    "description": "应用Id",
                    "type": "string"
                },
                "channelName": {
                    "description": "频道名字",
                    "type": "string"
                },
                "channelSId": {
                    "description": "频道会话Id",
                    "type": "string"
                },
                "eventType": {
                    "description": "Rtc消息通知类型",
                    "type": "integer"
                },
                "platform": {
                    "description": "平台()",
                    "type": "integer"
                },
                "reason": {
                    "description": "用户离开的原因",
                    "type": "integer"
                },
                "uSId": {
                    "description": "业务系统uId",
                    "type": "string"
                },
                "uid": {
                    "description": "业务系统uId",
                    "type": "string"
                }
            }
        },
        "models.ReqGetRoomList": {
            "type": "object",
            "properties": {
                "pageNum": {
                    "description": "页码（从1开始）",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "单页显示条数",
                    "type": "integer"
                },
                "roomState": {
                    "description": "房间状态(1:结束,2:进行中)",
                    "type": "integer"
                }
            }
        },
        "models.ReqInsertRoom": {
            "type": "object",
            "properties": {
                "isJoin": {
                    "description": "是否加入房间(1:是,2:否)",
                    "type": "integer"
                }
            }
        },
        "models.ReqInsertUserOnlineInfo": {
            "type": "object",
            "properties": {
                "optTs": {
                    "description": "心跳包时间戳(单位:秒)",
                    "type": "integer"
                },
                "uid": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "models.ReqJoinRoom": {
            "type": "object",
            "properties": {
                "roomId": {
                    "description": "房间id",
                    "type": "string"
                },
                "userRole": {
                    "description": "用户角色(1:主播,2:观众)",
                    "type": "integer"
                }
            }
        },
        "models.ReqLeaveRoom": {
            "type": "object",
            "properties": {
                "roomId": {
                    "description": "房间id",
                    "type": "string"
                },
                "uid": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "models.ReqSignIn": {
            "type": "object",
            "properties": {
                "uid": {
                    "description": "用户id(9位随机数字)",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                },
                "userType": {
                    "description": "用户类型(1:智能终端,2:专家,3:管理员)",
                    "type": "integer"
                },
                "workName": {
                    "description": "用户工种",
                    "type": "string"
                }
            }
        },
        "models.ReqTeamViewRtcNotify": {
            "type": "object",
            "properties": {
                "eventType": {
                    "description": "Rtc消息通知类型",
                    "type": "integer"
                },
                "noticeID": {
                    "description": "通知的id",
                    "type": "string"
                },
                "notifyMs": {
                    "description": "通知时间戳（单位：毫秒）",
                    "type": "integer"
                },
                "payload": {
                    "description": "请求包",
                    "type": "object",
                    "$ref": "#/definitions/models.Payload"
                },
                "productId": {
                    "description": "通知产品类型",
                    "type": "integer"
                },
                "secret": {
                    "description": "开发者通知服务用于签名的secret",
                    "type": "string"
                }
            }
        },
        "models.ReqTeamViewVodNotify": {
            "type": "object",
            "properties": {
                "eventType": {
                    "description": "Rtc消息通知类型",
                    "type": "integer"
                },
                "noticeID": {
                    "description": "通知的id",
                    "type": "string"
                },
                "notifyMs": {
                    "description": "通知时间戳（单位：毫秒）",
                    "type": "integer"
                },
                "payload": {
                    "description": "请求包",
                    "type": "object",
                    "$ref": "#/definitions/models.VodPayload"
                },
                "productId": {
                    "description": "通知产品类型",
                    "type": "integer"
                }
            }
        },
        "models.ReqUId": {
            "type": "object",
            "properties": {
                "uid": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "models.RespFinishedRoomList": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "房间列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FinishedRoomInfo"
                    }
                },
                "totalNum": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "models.RespGetSpecialist": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "专家信息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SpecialistUserInfo"
                    }
                },
                "totalNum": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "models.RespInsertRoom": {
            "type": "object",
            "properties": {
                "roomHostId": {
                    "description": "房主uid",
                    "type": "string"
                },
                "roomId": {
                    "description": "房间id",
                    "type": "string"
                },
                "roomName": {
                    "description": "房间名称",
                    "type": "string"
                },
                "roomState": {
                    "description": "房间状态(1:结束,2:进行中,3:转码中)",
                    "type": "integer"
                },
                "roomTs": {
                    "description": "房间创建时间戳(单位:秒)",
                    "type": "integer"
                },
                "rtcToken": {
                    "description": "rtcToken(不加入房间时为空)",
                    "type": "string"
                }
            }
        },
        "models.RespJoinRoom": {
            "type": "object",
            "properties": {
                "roomInfo": {
                    "description": "房间信息",
                    "type": "object",
                    "$ref": "#/definitions/models.RoomInfo"
                },
                "rtcToken": {
                    "description": "rtcToken",
                    "type": "string"
                }
            }
        },
        "models.RespOngoingRoomList": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "房间列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OnGoingRoomInfo"
                    }
                },
                "totalNum": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "models.RespSignIn": {
            "type": "object",
            "properties": {
                "appId": {
                    "description": "appId",
                    "type": "string"
                },
                "rtmToken": {
                    "description": "rtmToken",
                    "type": "string"
                },
                "uid": {
                    "description": "用户id",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                },
                "userTs": {
                    "description": "用户登录时间戳(单位:秒)",
                    "type": "integer"
                },
                "userType": {
                    "description": "用户类型(1:智能终端,2:专家,3:管理员)",
                    "type": "integer"
                },
                "workName": {
                    "description": "用户工种",
                    "type": "string"
                }
            }
        },
        "models.RespStartVodRecording": {
            "type": "object",
            "properties": {
                "Body": {
                    "description": "响应体",
                    "type": "object",
                    "$ref": "#/definitions/models.StartBody"
                },
                "Code": {
                    "description": "响应码",
                    "type": "integer"
                }
            }
        },
        "models.RoomInfo": {
            "type": "object",
            "properties": {
                "roomHostId": {
                    "description": "房主uid",
                    "type": "string"
                },
                "roomId": {
                    "description": "房间id",
                    "type": "string"
                },
                "roomName": {
                    "description": "房间名称",
                    "type": "string"
                },
                "roomState": {
                    "description": "房间状态(1:结束,2:进行中,3:转码中)",
                    "type": "integer"
                },
                "roomTs": {
                    "description": "房间创建时间戳(单位:秒)",
                    "type": "integer"
                },
                "roomVodResourceId": {
                    "description": "房间录像的resource ID",
                    "type": "string"
                },
                "roomVodSId": {
                    "description": "房间录像的录制 ID",
                    "type": "string"
                },
                "roomVodUId": {
                    "description": "房间录制在频道内使用的 UID",
                    "type": "string"
                }
            }
        },
        "models.SpecialistUserInfo": {
            "type": "object",
            "properties": {
                "roomId": {
                    "description": "专家所在房间id",
                    "type": "string"
                },
                "uid": {
                    "description": "用户id",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                },
                "userState": {
                    "description": "用户状态(1:通话中,2:空闲,3:离线)",
                    "type": "integer"
                },
                "userTs": {
                    "description": "用户登录时间戳(单位:秒)",
                    "type": "integer"
                },
                "userType": {
                    "description": "用户类型(1:智能终端,2:专家,3:管理员)",
                    "type": "integer"
                },
                "workName": {
                    "description": "用户工种",
                    "type": "string"
                }
            }
        },
        "models.StartBody": {
            "type": "object",
            "properties": {
                "resourceId": {
                    "description": "云端录制使用的 resource ID。",
                    "type": "string"
                },
                "sid": {
                    "description": "录制 ID。成功开始云端录制后，你会得到一个 sid （录制 ID)。该 ID 是一次录制周期的唯一标识。",
                    "type": "string"
                }
            }
        },
        "models.UserInfo": {
            "type": "object",
            "properties": {
                "uid": {
                    "description": "用户id",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                },
                "userTs": {
                    "description": "用户登录时间戳(单位:秒)",
                    "type": "integer"
                },
                "userType": {
                    "description": "用户类型(1:智能终端,2:专家,3:管理员)",
                    "type": "integer"
                },
                "workName": {
                    "description": "用户工种",
                    "type": "string"
                }
            }
        },
        "models.VodPayload": {
            "type": "object",
            "properties": {
                "cname": {
                    "description": "频道名字",
                    "type": "string"
                },
                "details": {
                    "description": "具体的消息内容(json)",
                    "type": "string"
                },
                "sendts": {
                    "description": "事件发生的时间戳（单位：毫秒）",
                    "type": "integer"
                },
                "sequence": {
                    "description": "消息序列号",
                    "type": "integer"
                },
                "serviceType": {
                    "description": "回调事件服务的类型(0:云端录制服务,1:录制服务,2:上传模块,4:扩展服务)",
                    "type": "integer"
                },
                "sid": {
                    "description": "业务系统sid",
                    "type": "string"
                },
                "uid": {
                    "description": "业务系统uid",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "192.168.1.140:12681",
	BasePath:    "/arapi/v1",
	Schemes:     []string{},
	Title:       "anyRTC arteamview server api server",
	Description: "This is a arteamview server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
