useConf = "d"
[dConfig]
  processName = "arteamviewservice"
  host = "0.0.0.0"
  port = 12681
  pidDir = "/run"

  customerId = ""
  customerCert = ""
  appId = ""
  appToken = ""
  devpSecret = ""

  ### second
  tokenExpire = 172800
  rtcTokenExpire = 2700
  rtmTokenExpire = 172800
  ### 查询用户心跳包间隔时间（单位：秒）
  onlineInterval = 30

  ### 录像服务接口前缀
  httpVodPrefix = "https://api.agrtc.cn"
  ### 录像文件播放下载地址前缀
  httpVodFilePrefix = "http://host:port/directory3/directory4/"

  # 录像文件保存天数
  vodValidDays = 30
  # Bucket对应的Endpoint，以华东1（杭州）为例，填写为https://oss-cn-hangzhou.aliyuncs.com
  ossEndpoint = ""

  #./web/views/
  webSource = "./web/views"

  ### 第三方云存储的配置信息(详见README.md文件说明)
  [dConfig.storageConfig]
    accessKey= ""
    region= 0
    bucket= "http://host:port/arapi/v1/fdfs/file/uploadOssFile"
    secretKey= ""
    vendor= 100
    fileNamePrefix= ["directory3", "directory4"]
  [dConfig.redis]
    port = 6379
    host = "127.0.0.1"
    family = 4
    password = ""
    db = 0
  [dConfig.mysql]
    user = "root"
    host = "127.0.0.1"
    port = 3306
    password = ""
    database = "ar_teamview"
  [dConfig.logger]
    logExpire = 3
    logDir = "/var/log/arteamviewservice"
    logName = "arteamviewservice.log"
    logLevel = 4
